#!/bin/bash

data_file="perf.data"

[ -f "perf_c2c.data" ] && data_file="perf_c2c.data" && echo $data_file

[ -f "perf-c2c.data" ] && data_file="perf-c2c.data" && echo $data_file

[ -n "$2" ] && data_file=$2


if [ -f "vmlinux" ]
then
	perf c2c report -NN -c iaddr --full-symbols -i $data_file -k vmlinux > c_$1_c2c.log 
	perf c2c report  --call-graph none -i $data_file -k vmlinux > s_$1_c2c.log
else
	perf c2c report -NN -c iaddr --full-symbols -i $data_file > c_$1_c2c.log 
	perf c2c report  --call-graph none -i $data_file > s_$1_c2c.log
fi


#perf c2c report -NN -c iaddr --full-symbols -i $data_file -k vmlinux --stdio > c_$1_c2c.log 
#perf c2c report --stdio --call-graph none -i $data_file -k vmlinux > s_$1_c2c.log


#perf c2c report -NN -c iaddr --full-symbols -i $data_file --kallsyms kallsyms --stdio > c_$1_c2c.log 
#perf c2c report --stdio --call-graph none -i $data_file --kallsyms kallsyms > s_$1_c2c.log

