#!/bin/bash
set -x

files=" pci-tdisp.c rpb.c tdisp.c drivers/pci/ide.c spdm_mgr.c pci-ide.c device-attest.c "

for file in $files
do
	echo "file $file +p " >  /sys/kernel/debug/dynamic_debug/control
done
