#!/bin/sh
#if [ $# -lt 1 ]; then
#	echo "tallindent Usage: tallindent [dir] ... "
#	exit 1
#fi

if [ ! -e "$1" ]
then
	echo '$1 is NULL'
	fdir=.
else
	echo "\$1 is $1"
	fdir=$1
fi

to_be_indented=$(sudo find $fdir -name *.[ch])
echo $to_be_indented

indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 $to_be_indented
