#!/bin/bash

cd /sys/devices/pci0000:00/0000:00:03.0/testcase/

echo 4096 > mem_size

for api in {0..2}
do
	echo $api
	echo $api > dma_api

	for attr in {1..2}
	do
		#define RPB_MEM_ATTR_NONE               0
		#define RPB_MEM_ATTR_DEFAULT            1
		#define RPB_MEM_ATTR_SHARED             2
		#define RPB_MEM_ATTR_MAX                3
		echo $attr > mem_attr

		echo $attr

		for op in {1..2}
		do
			echo $op
			echo $op > mem_op
			
			echo "----------------------------------------------"
			grep . *
			echo "----------------------------------------------"

			echo 1 > run
			echo "----------------------------------------------"
			echo
		done
	done
done
