#!/bin/bash
# Author: Feng Tang <feng.tang@intel.com>
#
# * New version adding Alek Du's interactive op
# * use bash to use array[]
#
# files=(a b c d e f g h i j k l m n o p q r s t)

# Declare a array

set -x


if [ -e "$1" ]
then
	vi $1 
	exit
fi

if [ -e "$2" ]
then
	cwd=$2
else
	cwd=.
fi

#files_name=`find . -name "$1" | sed -e "/.*.o$/d"`
files_name=`find $cwd -name "$1" | sed -e "/.*.o$/d"`

select file in $files_name
do
	break
done

vi $file

